# Generated by Django 2.2 on 2020-12-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobson_digs_app', '0003_auto_20201212_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_post_logo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
